name: Example workflow

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
#   push:
#     ### can be further specified
#     branch: branchName/*/

#   pull_request:
#     types:
#       ### defaults:
#       - opened
#       - synchronize
#       - reopened

#   schedule:
#     ###      M H D M J
#     - cron: "0 0 * * *" # Midnight UTC

env:
  WFVAR: WORKFLOW-SCOPED-VARIABLE

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      JBVAR: JOB-SCOPED-VARIABLE
    steps:
      ### Step-1:
      - name: "Step-1"
        env:
          STVAR: STEP-SCOPED-VARIABLE
        run: echo "$STVAR Hello "
      ### Step-2
      - run: echo "$STVAR World!"

  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: print("Hello pyWorld!")
        shell: python
  job-3:
    runs-on: ubuntu-latest
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "Job 1&2 done"
